### PR TITLE
Added Lie Detector

### PR DESCRIPTION
**Pull request by RosalinaFan573**
Merge please!

### CODE REVIEW

**Comment by Cruel** [comment]
Looks good, just need to rehost image on imgur. A bit restrictive, but prevents people from changing image after merge. After that, it can be merged.

**Comment by RosalinaFan573** [comment]
Changed it, does it apply to this pull request?

**Comment by Cruel** [comment]
If you push it to your repo, it should add it to this PR.

**Comment by RosalinaFan573** [comment]
I guess you can merge it.

**Comment by Cruel** [comment]
Haha, silly bot.

**Comment by RosalinaFan573** [comment]
So I have to combine the commits?

**Comment by RosalinaFan573** [comment]
http://i.imgur.com/twsN2Xp.png
Can you change the screenshot URL to that?

**Pull request merged**
