### PR TITLE
Added Reversi

### PR DESCRIPTION
**Pull request by MrJPGames**
Added my homebrew adaptation of Reversi. 
Currently the download points to: https://github.com/MrJPGames/Othello-3DS/releases/download/1.1/Reversi.zip

### CODE REVIEW

**Comment by Cruel** [comment]
Okay, don't worry about the permissions errors, I can add you to whitelist.

However, you put this in the Reversi directory, and the game in the archive is in Othello directory. Fixing that should be all you need to do. It will expect a `/3ds/<dir>/<dir>.3dsx`

You can make an amended commit to fix and then push -f

**Comment by MrJPGames** [comment]
Ok, as Reversi is the actual name of the homebrew (Othello is kind of a left over from development) I changed the name in Reversi.zip to reversi.
So now the files in the archieve are: /3ds/Reversi/Reversi.3dsx and /3ds/Reversi/Reversi.sdmc
But because this means all changes are in the release .zip and not in the repo i cannot ammend any commits.

EDIT: btw. Should I add the homebrew+my username to the permission list (now and) in the future? Or will the bot handle that automaticly?

**Comment by Cruel** [comment]
You will need to amend filesize/md5 when you change the archive file. That should be it.

And yeah, add yourself to the permissions file.

**Comment by Cruel** [comment]
If you're not sure, this shows you how to use git rebase to squash commits:

http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

If you squash all 4 into 1, then you can do a "push -f" to your fork. Otherwise it will complain that you rebased commits already pushed. You normally don't want to do this if anyone else is using your branch, because it messes up base commits they may be using, but I'm guessing you're the only one using your fork of BrewRepo :stuck_out_tongue: so it should be fine.

**Comment by MrJPGames** [comment]
Thanks, it worked!

**Comment by Cruel** [comment]
Thanks!

Now you should have permissions for Reversi. If you ever update it in the future, it won't give you the permission errors and the bot will auto-merge it (hopefully instantly, if it's running).

**Pull request merged**
